version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: escola-postgres
    environment:
      POSTGRES_DB: escola_ingles_db
      POSTGRES_USER: escola_ingles_stefanini
      POSTGRES_PASSWORD: "180318"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: