spring:
  application:
    name: escola-ingles-api

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/escola_ingles_db
    username: escola_user
    password: escola_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always